import os
import re

def get_major_version(cmakelists_path):
    if not os.path.exists(cmakelists_path):
        return None
    with open(cmakelists_path, "r") as f:
        for line in f:
            match = re.search(r"set\(LIB_VER_MAJOR (\d+)\)", line)
            if match:
                return match.group(1)
    return None

def patch_gz_vendor(package_path):
    cmakelists_path = os.path.join(package_path, "CMakeLists.txt")
    if not os.path.exists(cmakelists_path):
        print(f"Skipping {package_path}, no CMakeLists.txt found.")
        return

    major_version = get_major_version(cmakelists_path)
    # Determine names (e.g., gz-cmake5 and gz-cmake)
    pkg_basename = os.path.basename(package_path).replace("_vendor", "").replace("_", "-")
    
    if major_version:
        versioned_name = f"{pkg_basename}{major_version}"
    else:
        versioned_name = pkg_basename
    
    unversioned_name = pkg_basename

    with open(cmakelists_path, "r") as f:
        content = f.read()

    # Add ament_export_dependencies if the versioned name is not being exported
    if "ament_export_dependencies" not in content:
        export_dep = f"\nament_export_dependencies({versioned_name} {unversioned_name})\n"
        content = content.replace("ament_package()", export_dep + "ament_package()")
        print(f"Adding ament_export_dependencies to {cmakelists_path}")
    elif versioned_name not in content:
        # It has ament_export_dependencies but not our library
        pattern = r"(ament_export_dependencies\()(.+?)(\))"
        replacement = rf"\1\2 {versioned_name} {unversioned_name}\3"
        content = re.sub(pattern, replacement, content)
        print(f"Appending {versioned_name} to ament_export_dependencies in {cmakelists_path}")

    # Convert any existing CONFIG_EXTRAS_POST to CONFIG_EXTRAS
    if "CONFIG_EXTRAS_POST" in content:
        content = content.replace("CONFIG_EXTRAS_POST", "CONFIG_EXTRAS")
        print(f"Changed CONFIG_EXTRAS_POST to CONFIG_EXTRAS in {cmakelists_path}")

    # Add CONFIG_EXTRAS to ament_package if missing
    extras_file = f"{os.path.basename(package_path)}-extras.cmake.in"
    if "CONFIG_EXTRAS" not in content:
        content = content.replace("ament_package()", f"ament_package(\n  CONFIG_EXTRAS \"{extras_file}\"\n)")
        print(f"Adding CONFIG_EXTRAS to {cmakelists_path}")

    with open(cmakelists_path, "wb") as f:
        f.write(content.encode('utf-8').replace(b'\r\n', b'\n'))

    # Create the extras file
    extras_path = os.path.join(package_path, extras_file)
    # Broaden fallback search for Gazebo-style directory structures
    # On Windows, we need to add the bin directory to the PATH for DLLs
    extras_content = f"""# Generated by patch_gazebo.py
find_package(ament_cmake_core REQUIRED)
set(@PROJECT_NAME@_PREFIX "${{@PROJECT_NAME@_DIR}}/../../../opt/@PROJECT_NAME@")

# Add the vendored package to the prefix path
list(APPEND CMAKE_PREFIX_PATH "${{@PROJECT_NAME@_PREFIX}}")

# For Gazebo packages specifically
list(APPEND CMAKE_PREFIX_PATH "${{@PROJECT_NAME@_PREFIX}}/share")

if(WIN32)
  # Add bin to PATH for DLL discovery
  ament_prepend_variable_by_name(PATH "${{@PROJECT_NAME@_PREFIX}}/bin")
endif()

# Fallback for unversioned vs versioned names (e.g. {pkg_basename} vs {versioned_name})
if(NOT {versioned_name}_FOUND)
    # Try finding the unversioned name and then aliasing it
    find_package({unversioned_name} QUIET)
    if({unversioned_name}_FOUND)
        set({versioned_name}_FOUND ON)
        # Some packages use <PKG>_INCLUDE_DIRS, etc.
        set({versioned_name}_INCLUDE_DIRS ${{{unversioned_name}_INCLUDE_DIRS}})
        set({versioned_name}_LIBRARIES ${{{unversioned_name}_LIBRARIES}})
        set({versioned_name}_LIBRARY_DIRS ${{{unversioned_name}_LIBRARY_DIRS}})
    endif()
endif()
"""
    with open(extras_path, "wb") as f:
        f.write(extras_content.encode('utf-8').replace(b'\r\n', b'\n'))
    print(f"Created/Updated {extras_path}")

if __name__ == "__main__":
    base_path = "src/gazebo-release"
    if not os.path.exists(base_path):
        print(f"Base path {base_path} not found.")
    else:
        for pkg in os.listdir(base_path):
            full_path = os.path.join(base_path, pkg)
            if os.path.isdir(full_path) and pkg.endswith("_vendor"):
                patch_gz_vendor(full_path)
