import os
import re
import subprocess
import sys

def git_reset(path):
    pkg_dir = os.path.dirname(path)
    while pkg_dir and not os.path.exists(os.path.join(pkg_dir, '.git')):
        next_dir = os.path.dirname(pkg_dir)
        if next_dir == pkg_dir:
            pkg_dir = None
            break
        pkg_dir = next_dir
    
    if pkg_dir:
        rel_path = os.path.relpath(path, pkg_dir)
        subprocess.run(["git", "checkout", "--", rel_path], cwd=pkg_dir, capture_output=True)

def patch_gz_vendor(package_path):
    cmakelists_path = os.path.join(package_path, "CMakeLists.txt")
    if not os.path.exists(cmakelists_path):
        return

    git_reset(cmakelists_path)

    pkg_name = os.path.basename(package_path)
    pkg_basename = pkg_name.replace("_vendor", "").replace("_", "-")
    
    with open(cmakelists_path, "r") as f:
        content = f.read()
        match = re.search(r"set\(LIB_VER_MAJOR (\d+)\)", content)
        if match:
            major_version = match.group(1)
        else:
            if "cmake" in pkg_name: major_version = "3"
            elif "math" in pkg_name: major_version = "7"
            elif "utils" in pkg_name: major_version = "2"
            else: major_version = ""

    versioned_name = f"{pkg_basename}{major_version}"
    unversioned_name = pkg_basename

    # 1. Add ament_export_dependencies
    # We want to export both names
    export_dep = f"ament_export_dependencies({versioned_name} {unversioned_name})\n"
    if "ament_export_dependencies" not in content:
        content = content.replace("ament_package()", export_dep + "ament_package()")
    
    # 2. Add CONFIG_EXTRAS
    # We'll create a single extras file that acts as a relay
    extras_file = f"{pkg_name}-extras.cmake.in"
    if "CONFIG_EXTRAS" not in content:
        content = content.replace("ament_package()", f"ament_package(CONFIG_EXTRAS {extras_file})")

    with open(cmakelists_path, "w") as f:
        f.write(content)

    # 3. Create the extras.cmake.in file
    # This file will:
    # a) Setup CMAKE_PREFIX_PATH to find the vendored package
    # b) Create relay files for both versioned and unversioned names
    lines = [
        "# Generated by patch_gazebo.py",
        "set(@PROJECT_NAME@_OPT_DIR \"${@PROJECT_NAME@_DIR}/../../../opt/@PROJECT_NAME@\")",
        "",
        "# Add the vendored package to the prefix path",
        "list(APPEND CMAKE_PREFIX_PATH \"${@PROJECT_NAME@_OPT_DIR}\")",
        "list(APPEND CMAKE_PREFIX_PATH \"${@PROJECT_NAME@_OPT_DIR}/share\")",
        "",
        "# Dynamically create Config relay files in the install directory",
        "macro(create_gz_relay _name)",
        "  if(NOT EXISTS \"${@PROJECT_NAME@_DIR}/${_name}Config.cmake\")",
        "    file(WRITE \"${@PROJECT_NAME@_DIR}/${_name}Config.cmake\"",
        "      \"set(${_name}_DIR \\\"${@PROJECT_NAME@_OPT_DIR}/share/cmake/" + unversioned_name + "\\\")\\n\"",
        "      \"if(NOT EXISTS \\\"\\${${_name}_DIR}\\\")\\n\"",
        "      \"  set(${_name}_DIR \\\"${@PROJECT_NAME@_OPT_DIR}/lib/cmake/" + unversioned_name + "\\\")\\n\"",
        "      \"endif()\\n\"",
        "      \"find_package(" + unversioned_name + " REQUIRED NO_DEFAULT_PATH)\\n\"",
        "      \"if(" + unversioned_name + "_FOUND)\\n\"",
        "      \"  set(${_name}_FOUND ON)\\n\"",
        "      \"  if(NOT TARGET " + unversioned_name + "::core AND TARGET " + unversioned_name + "::" + unversioned_name + ")\\n\"",
        "      \"    add_library(" + unversioned_name + "::core ALIAS " + unversioned_name + "::" + unversioned_name + ")\\n\"",
        "      \"  endif()\\n\"",
        "      \"  if(NOT TARGET " + versioned_name + "::" + versioned_name + " AND TARGET " + unversioned_name + "::" + unversioned_name + ")\\n\"",
        "      \"    add_library(" + versioned_name + "::" + versioned_name + " ALIAS " + unversioned_name + "::" + unversioned_name + ")\\n\"",
        "      \"  endif()\\n\"",
        "      \"  if(NOT TARGET " + unversioned_name + "::" + unversioned_name + " AND TARGET " + versioned_name + "::" + versioned_name + ")\\n\"",
        "      \"    add_library(" + unversioned_name + "::" + unversioned_name + " ALIAS " + versioned_name + "::" + versioned_name + ")\\n\"",
        "      \"  endif()\\n\"",
        "      \"endif()\\n\"",
        "    )",
        "  endif()",
        "endmacro()",
        "",
        f"create_gz_relay({versioned_name})",
        f"create_gz_relay({unversioned_name})",
    ]
    extras_content = "\n".join(lines) + "\n"

    with open(os.path.join(package_path, extras_file), "w") as f:
        f.write(extras_content)
    print(f"Patched {pkg_name}")

if __name__ == "__main__":
    base_path = "src/gazebo-release"
    if os.path.exists(base_path):
        for pkg in os.listdir(base_path):
            full_path = os.path.join(base_path, pkg)
            if os.path.isdir(full_path) and pkg.endswith("_vendor"):
                patch_gz_vendor(full_path)
