import os
import re

def patch_gz_vendor(package_path, vendored_name):
    cmakelists_path = os.path.join(package_path, "CMakeLists.txt")
    if not os.path.exists(cmakelists_path):
        print(f"Skipping {package_path}, no CMakeLists.txt found.")
        return

    with open(cmakelists_path, "r") as f:
        content = f.read()

    # Add ament_export_dependencies if missing
    if "ament_export_dependencies" not in content:
        export_dep = f"\nament_export_dependencies({vendored_name})\n"
        content = content.replace("ament_package()", export_dep + "ament_package()")
        print(f"Adding ament_export_dependencies to {cmakelists_path}")

    # Add CONFIG_EXTRAS_POST to ament_package if missing
    extras_file = f"{os.path.basename(package_path)}-extras.cmake.in"
    if "CONFIG_EXTRAS_POST" not in content:
        content = content.replace("ament_package()", f"ament_package(\n  CONFIG_EXTRAS_POST \"{extras_file}\"\n)")
        print(f"Adding CONFIG_EXTRAS_POST to {cmakelists_path}")

    with open(cmakelists_path, "w") as f:
        f.write(content)

    # Create the extras file
    extras_path = os.path.join(package_path, extras_file)
    if not os.path.exists(extras_path):
        with open(extras_path, "w") as f:
            f.write(f"""# Generated by patch_gazebo.py
find_package(ament_cmake_core REQUIRED)
ament_cmake_get_parent_prefix(parent_prefix)
set(@PROJECT_NAME@_PREFIX "${{@PROJECT_NAME@_DIR}}/../../../opt/@PROJECT_NAME@")
list(APPEND CMAKE_PREFIX_PATH "${{@PROJECT_NAME@_PREFIX}}")
""")
        print(f"Created {extras_path}")

if __name__ == "__main__":
    base_path = "src/gazebo-release"
    packages = [
        ("gz_cmake_vendor", "gz-cmake"),
        ("gz_utils_vendor", "gz-utils"),
        ("gz_math_vendor", "gz-math")
    ]
    
    for pkg, vendored in packages:
        full_path = os.path.join(base_path, pkg)
        if os.path.exists(full_path):
            patch_gz_vendor(full_path, vendored)
        else:
            print(f"Package {pkg} not found in {base_path}")
