name: Pixi-based CI
on: [push, pull_request]

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      BUILDCACHE_MAX_CACHE_SIZE: 2000000000                        # optional: Need a bigger cache?
      # BUILDCACHE_LOG_FILE: ${{ matrix.label }}.buildcache.log    # optional: include log output
      # BUILDCACHE_DEBUG: 2                                        # optional: debug level, less is more
      BUILDCACHE_DIRECT_MODE: true                                 # optional: Allow direct caching
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.9.1
          cache: true
      - uses: mjcarroll/buildcache-action@v2
        with:
          cache_key: ${{ matrix.label }}
          upload_buildcache_log: 'false'
          zero_buildcache_stats: 'true'
      - run: pixi run sync
      - run: pixi run build --continue-on-error
